FROM nginx:latest
RUN apt update && apt -y install keepalived
COPY nginx.conf /etc/nginx/nginx.conf
ARG role
COPY keepalived-${role}.conf /etc/keepalived/keepalived.conf
RUN chmod -x /etc/keepalived/keepalived.conf
COPY start.sh /start.sh
CMD ["/start.sh"]
